CFT-3221 Update: Set region
keboola/looker-writer pull request #38
Opened 2024-11-12 09:12 UTC by themark147

2024-11-19 08:31 UTC, ondrajodas reviewed
jedna věc + 
\- prosím doplň description PR
\- a do názvu branche se podepisuj, třeba `CF-3221-marek`

2024-11-19 08:31 UTC, ondrajodas commented on src/DbBackend/BigQueryBackend.php
> +                'location' => $this->config->getLocation(),
tady by si ho měl nastavit jen pokud je v konfiguraci skutečně nastavený, jinak to nebude kompatibilní se starýma konfiguracema

2024-11-19 10:03 UTC, themark147 commented
> jedna věc + - prosím doplň description PR - a do názvu branche se podepisuj, třeba `CF-3221-marek`

ju jasne dik dalsie PR takto vytvorim ... vychadzal som btw z tohto https://keboola.atlassian.net/wiki/spaces/CF/pages/1412071812/Working+with+GIT#Create-a-branch

2024-11-21 08:37 UTC, ondrajodas commented on src/DbBackend/BigQueryBackend.php
> +                'location' => $this->config->getLocation(),
tohle nevidím vyřešený??

2024-11-21 08:38 UTC, ondrajodas requested changes
nevidím vyřešený poslední komentář

2024-11-21 08:39 UTC, themark147 commented
> nevidím vyřešený poslední komentář

no ak zmenin nazov branche budem musiet vytvorit novy PR nie?

2024-11-21 08:41 UTC, ondrajodas commented
tohle myslím - https://github.com/keboola/looker-writer/pull/38#discussion_r1847882513

2024-11-21 08:46 UTC, ondrajodas commented
a nezapoměň k tomu test že nebude nastavený ;)

2024-11-21 09:47 UTC, themark147 commented
> a nezapomeň k tomu test že nebude nastavený ;)

no prave historicky tam uz taky je

2024-11-21 09:54 UTC, ondrajodas commented
ok tak alespoň tady - https://github.com/keboola/looker-writer/blob/master/tests/phpunit/ConfigTest.php by mělo být otestovaný že to vrací to co tam pošleš

2024-11-21 10:47 UTC, themark147 commented
> ok tak alespoň tady - https://github.com/keboola/looker-writer/blob/master/tests/phpunit/ConfigTest.php by mělo být otestovaný že to vrací to co tam pošleš

tak snad uz je tam zapracovane vsetko 😁

2024-11-21 11:12 UTC, ondrajodas approved these changes
jo takhle už OK :)

2024-11-21 11:44 UTC, merged